// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY8ndwYOfkZ43AHnO2bmFRB18iHQsj480',
    appId: '1:7689513589:web:149d2dfa72b4a759cfa63c',
    messagingSenderId: '7689513589',
    projectId: 'chat-app-pody',
    authDomain: 'chat-app-pody.firebaseapp.com',
    storageBucket: 'chat-app-pody.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkGd2I8uDunarKDTVACGkovJT9cuS-fVE',
    appId: '1:7689513589:android:474b34c89f3f1af7cfa63c',
    messagingSenderId: '7689513589',
    projectId: 'chat-app-pody',
    storageBucket: 'chat-app-pody.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYbDRqJD8oXAGGTf8vLnZFgaPmO7Nq-8g',
    appId: '1:7689513589:ios:55292e4833ad033bcfa63c',
    messagingSenderId: '7689513589',
    projectId: 'chat-app-pody',
    storageBucket: 'chat-app-pody.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYbDRqJD8oXAGGTf8vLnZFgaPmO7Nq-8g',
    appId: '1:7689513589:ios:55292e4833ad033bcfa63c',
    messagingSenderId: '7689513589',
    projectId: 'chat-app-pody',
    storageBucket: 'chat-app-pody.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY8ndwYOfkZ43AHnO2bmFRB18iHQsj480',
    appId: '1:7689513589:web:4daaf94a5fffda8ccfa63c',
    messagingSenderId: '7689513589',
    projectId: 'chat-app-pody',
    authDomain: 'chat-app-pody.firebaseapp.com',
    storageBucket: 'chat-app-pody.firebasestorage.app',
  );
}
